import type { BenchmarkFixture } from "./bandFlipHarness";

/**
 * Benchmark fixtures for band-flip testing.
 * Each fixture represents a known-quality answer at a specific level.
 * Fixtures cover all evaluation dimensions and difficulty levels.
 */
export const BENCHMARK_FIXTURES: BenchmarkFixture[] = [
  {
    id: "dsa-easy-strong",
    questionText: "What is a stack and how is it different from a queue?",
    category: "DSA",
    difficulty: "easy",
    transcript: "A stack is a linear data structure that follows the Last In First Out or LIFO principle. The element that is inserted last is the first one to be removed. Think of it like a pile of plates — you can only take from the top. A queue, on the other hand, follows First In First Out or FIFO. The element inserted first is removed first, like a line at a ticket counter. The key difference is the order of removal. In a stack, we use push and pop operations. In a queue, we use enqueue and dequeue. Both are used in different scenarios — stacks are used in function call management, undo operations, and DFS traversal. Queues are used in BFS, task scheduling, and print job management.",
    durationMs: 45000,
    expectedContentBand: "strong",
    expectedStructureBand: "strong",
    expectedDeliveryBand: "solid",
    expectedOverallBand: "strong",
    tags: ["clear-definition", "good-examples", "well-structured"],
  },
  {
    id: "dbms-medium-solid",
    questionText: "Explain database normalization up to 3NF.",
    category: "DBMS",
    difficulty: "medium",
    transcript: "Normalization is a process of organizing data in a database to reduce redundancy. First normal form or 1NF requires that each column contains atomic values and there are no repeating groups. Second normal form or 2NF requires that the table is in 1NF and all non-key attributes are fully functionally dependent on the primary key. Third normal form or 3NF requires that the table is in 2NF and there are no transitive dependencies. For example, if we have a student table with student ID, department, and department head, the department head depends on the department, not directly on the student ID. That's a transitive dependency. We would split this into two tables to achieve 3NF.",
    durationMs: 38000,
    expectedContentBand: "solid",
    expectedStructureBand: "solid",
    expectedDeliveryBand: "solid",
    expectedOverallBand: "solid",
    tags: ["correct-explanation", "some-examples", "organized"],
  },
  {
    id: "os-easy-needs-work",
    questionText: "What is a process in an operating system?",
    category: "OS",
    difficulty: "easy",
    transcript: "A process is basically a program that is running. Like when you open Chrome it becomes a process. The operating system manages processes and gives them memory and CPU time. Processes have their own memory space unlike threads. There are different states of a process like ready, running, waiting. The OS scheduler decides which process runs when.",
    durationMs: 20000,
    expectedContentBand: "needs_work",
    expectedStructureBand: "needs_work",
    expectedDeliveryBand: "solid",
    expectedOverallBand: "needs_work",
    tags: ["incomplete", "missing-details", "basic"],
  },
  {
    id: "systemdesign-hard-strong",
    questionText: "Design a URL shortener like bit.ly.",
    category: "SystemDesign",
    difficulty: "hard",
    transcript: "A URL shortener needs three core operations: create a short URL from a long URL, redirect using the short URL, and track analytics. The architecture starts with a web server that receives the create request. We need a hash function to generate a unique short code — I'd use base62 encoding of an auto-incrementing ID or a hash of the long URL. For storage, we use a key-value store mapping the short code to the original URL, with the short code as the primary key. For redirection, we look up the short code and return a 301 redirect. For analytics, we log each redirect event asynchronously to avoid slowing down the redirect path. To handle high traffic, we add a Redis cache for frequently accessed URLs. For uniqueness at scale, we can use a distributed ID generator like Snowflake or pre-allocate ranges to different servers. The database can be sharded by the short code hash.",
    durationMs: 55000,
    expectedContentBand: "strong",
    expectedStructureBand: "strong",
    expectedDeliveryBand: "solid",
    expectedOverallBand: "strong",
    tags: ["comprehensive", "architecture", "scalability"],
  },
  {
    id: "behavioral-medium-solid",
    questionText: "Tell me about a time you had to work with a difficult team member.",
    category: "Behavioral",
    difficulty: "medium",
    transcript: "In my previous project, I worked with a colleague who had very different communication styles. They would often interrupt during meetings and dismiss ideas quickly. Instead of confronting them directly, I scheduled a one-on-one coffee chat. I asked about their perspective on the project and listened actively. I realized they were under pressure from another deadline and were feeling unheard themselves. We agreed on ground rules for meetings — each person gets two minutes uninterrupted. Over time, the collaboration improved significantly. The project shipped on time and the team morale got better. I learned that understanding the root cause of behavior is more productive than reacting to the behavior itself.",
    durationMs: 42000,
    expectedContentBand: "strong",
    expectedStructureBand: "strong",
    expectedDeliveryBand: "solid",
    expectedOverallBand: "strong",
    tags: ["star-method", "self-aware", "resolution"],
  },
  {
    id: "networks-easy-solid",
    questionText: "What is the difference between TCP and UDP?",
    category: "Networks",
    difficulty: "easy",
    transcript: "TCP stands for Transmission Control Protocol and UDP stands for User Datagram Protocol. TCP is connection-oriented — it establishes a three-way handshake before sending data. It guarantees delivery, ordering, and error checking. UDP is connectionless — it just sends data without establishing a connection first. It does not guarantee delivery or ordering. TCP is used where reliability matters like web browsing, email, and file transfer. UDP is used where speed matters more than reliability like video streaming, online gaming, and DNS lookups. TCP is slower because of the overhead of maintaining the connection. UDP is faster because it has minimal overhead.",
    durationMs: 32000,
    expectedContentBand: "solid",
    expectedStructureBand: "strong",
    expectedDeliveryBand: "solid",
    expectedOverallBand: "solid",
    tags: ["correct-comparison", "good-examples", "organized"],
  },
];
